const prompts = { 
  "day1": { "name": "Day and Night", "file": "day1", thumbnail: true}, 
  "day2": { "name": "Futurism", "file": "day2", thumbnail: true}, 
  "day3": { "name": "Archeology", "file": "day3", thumbnail: true}, 
  "day4": { "name": "Life & Growth", "file": "day4", thumbnail: true }, 
  "day5": { "name": "Death & Decay", "file": "day5", thumbnail: true }, 
  "day6": { "name": "Loud", "file": "day6", thumbnail: true }, 
  "day7": { "name": "The pixel.", "file": "day7" }, 
  "day8": { "name": "Capital R Romantic", "file": "day8" }, 
  "day9": { "name": "Heartbeat", "file": "day9" }, 
  "day10": { "name": "Games are art and you cannot let anyone tell you otherwise", "file": "day10" }, 
  "day11": { "name": "Elemental", "file": "day11", thumbnail: false }, 
  "day12": { "name": "Be small, do crimes", "file": "day12", thumbnail: true }, 
  "day13": { "name": "A chain of blocks but NOT blockchain okay? Idk man figure it out", "file": "day13", thumbnail: true }, 
  "day14": { "name": "Under construction", "file": "day14", thumbnail: true }, 
  "day15": { "name": "Delicious", "file": "day15" }, 
  "day16": { "name": "Spirit week (like, with regard to ghosts. Also it’s still just one day)", "file": "day16" }, 
  "day17": { "name": "Decades day", "file": "day17" }, 
  "day18": { "name": "A dog with a stick", "file": "day18" }, 
  "day19": { "name": "Tiny", "file": "day19" }, 
  "day20": { "name": "Invasive species", "file": "day20" }, 
  "day21": { "name": "Pick a piece of non-digital art and reference it, but I swear if it’s Mondrian you’re gonna get a bonk.", "file": "day21" }, 
  "day22": { "name": "Justice", "file": "day22" }, 
  "day23": { "name": "I love mess", "file": "day23" }, 
  "day24": { "name": "You ever think about like, your regrets in life?", "file": "day24" }, 
  "day25": { "name": "Automaton", "file": "day25" }, 
  "day26": { "name": "Memphis to Miami", "file": "day26" }, 
  "day27": { "name": "Dot dot dot", "file": "day27" }, 
  "day28": { "name": "Language arts", "file": "day28" }, 
  "day29": { "name": "Just vibes", "file": "day29" }, 
  "day30": { "name": "ActuallyGoodFinal_final-v2.png", "file": "day30" }, 
  "day31": { "name": "WILD CARD HALLOWEEN", "file": "day31" } 
};

module.exports = prompts;
