const prompts = { 
  "day1": { "name": "Day and Night", "file": "day1", thumbnail: true}, 
  "day2": { "name": "Futurism", "file": "day2", thumbnail: true}, 
  "day3": { "name": "Archeology", "file": "day3", thumbnail: true}, 
  "day4": { "name": "Life & Growth", "file": "day4", thumbnail: true }, 
  "day5": { "name": "Death & Decay", "file": "day5", thumbnail: true }, 
  "day6": { "name": "Loud", "file": "day6", thumbnail: true }, 
  "day7": { "name": "The pixel.", "file": "day7" }, 
  "day8": { "name": "Capital R Romantic", "file": "day8", thumbnail: true }, 
  "day9": { "name": "Heartbeat", "file": "day9" }, 
  "day10": { "name": "Games are art and you cannot let anyone tell you otherwise", "file": "day10" }, 
  "day11": { "name": "Elemental", "file": "day11", thumbnail: true }, 
  "day12": { "name": "Be small, do crimes", "file": "day12", thumbnail: true }, 
  "day13": { "name": "A chain of blocks but NOT blockchain okay? Idk man figure it out", "file": "day13", thumbnail: true }, 
  "day14": { "name": "Under construction", "file": "day14", thumbnail: true }, 
  "day15": { "name": "Delicious", "file": "day15", thumbnail: true }, 
  "day16": { "name": "Spirit week (like, with regard to ghosts. Also it’s still just one day)", "file": "day16" }, 
  "day17": { "name": "Decades day", "file": "day17" }, 
  "day18": { "name": "A dog with a stick", "file": "day18" }, 
  "day19": { "name": "Tiny", "file": "day19", thumbnail: true }, 
  "day20": { "name": "Invasive species", "file": "day20" }, 
  "day21": { "name": "Pick a piece of non-digital art and reference it, but I swear if it’s Mondrian you’re gonna get a bonk.", "file": "day21" }, 
  "day22": { "name": "Justice", "file": "day22" }, 
  "day23": { "name": "I love mess", "file": "day23" }, 
  "day24": { "name": "You ever think about like, your regrets in life?", "file": "day24" }, 
  "day25": { "name": "Automaton", "file": "day25" }, 
  "day26": { "name": "Memphis to Miami", "file": "day26" }, 
  "day27": { "name": "Dot dot dot", "file": "day27" }, 
  "day28": { "name": "Language arts", "file": "day28" }, 
  "day29": { "name": "Just vibes", "file": "day29" }, 
  "day30": { "name": "ActuallyGoodFinal_final-v2.png", "file": "day30" }, 
  "day31": { "name": "WILD CARD HALLOWEEN", "file": "day31" },
  "g4": { "name": "Genuary day 4: The Next Next Fidenza", "file":"g4", thumbnail: true},
  "g5": { "name": "Genuary day 5: Destroy a Square", "file":"g5", thumbnail: true},
  "g2": { "name": "Genuary day 2: Dithering", "file":"g2", thumbnail: true},
  "g7": { "name": "Genuary day 7: Sol LeWitt Wall Drawing", "file":"g7", thumbnail: true},
  "g8": { "name": "Genuary day 8: Single curve only", "file":"g8", thumbnail: true},
  "g9": { "name": "Genuary day 9: Architecture", "file":"g9", thumbnail: true},
  "g10": { "name": "Genuary day 10: Machine learning, wrong answers only", "file":"g10"},
  "g11": { "name": "Genuary day 11: No computer", "file":"g11"},
  "g12": { "name": "Genuary day 12: Packing", "file":"g12", thumbnail: true},
  "g13": { "name": "Genuary day 13: 80x800", "file":"g13", thumbnail: true},
  "g14": { "name": "Genuary day 14: Something you'd never make", "file":"g14", thumbnail: true, thumbnailName: "g14.gif"},
  "g15": { "name": "Genuary day 15: Sand", "file":"g15"},
  "g16": { "name": "Genuary day 16: Color gradients gone wrong", "file":"g16"},
  "g17": { "name": "Genuary day 17: Three colors", "file":"g17", thumbnail: true},
  "g18": { "name": "Genuary day 18: VHS", "file":"g18"},
  "g19": { "name": "Genuary day 19: Text/typography", "file":"g19"},
  "g20": { "name": "Genuary day 20: Sea of shapes", "file":"g20"},
  "g21": { "name": "Genuary day 21: Combine two previous pieces", "file":"g21"},
  "g22": { "name": "Genuary day 22: Something that will look different in a year", "file":"g22"},
  "g23": { "name": "Genuary day 23: Abstract vegetation", "file":"g23"},
  "g24": { "name": "Genuary day 24: Pseudo-random number generator", "file":"g24"},
  "g25": { "name": "Genuary day 25: Perspective", "file":"g25"},
  "g26": { "name": "Genuary day 26: Airport carpet", "file":"g26"},
  "g27": { "name": "Genuary day 27: #2E294E #541388 #F1E9DA #FFD400 #D90368", "file":"g27"},
  "g28": { "name": "Genuary day 28: Self portrait", "file":"g28"},
  "g29": { "name": "Genuary day 29: Isometric perspective", "file":"g29"},
  "g30": { "name": "Genuary day 30: Organic looking, rectangles only", "file":"g30"},
  "g31": { "name": "Genuary day 31: Negative space", "file":"g31"}
};

module.exports = prompts;
